---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: password
      prompt: "Enter local administrator password"

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: becomeansible-dev
        location: eastus

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: becomeansible-dev
        name: vnet-winweb
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: becomeansible-dev
        name: snet-winweb
        address_prefix: "10.0.1.0/24"
        virtual_network: vnet-winweb

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: becomeansible-dev
        allocation_method: Static
        name: pip-winweb
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: becomeansible-dev
        name: nsg-winweb
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: 'allow_powershell_remoting'
            protocol: Tcp
            destination_port_range:
              - 5985
              - 5986
            access: Allow
            priority: 1003
            direction: Inbound

    - name: Create a network interface
      azure_rm_networkinterface:
        name: nic-winweb
        resource_group: becomeansible-dev
        virtual_network: vnet-winweb
        subnet_name: snet-winweb
        security_group: nsg-winweb
        ip_configurations:
          - name: default
            public_ip_address_name: pip-winweb
            primary: True


    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: becomeansible-dev
        name: vm-winweb01
        vm_size: Standard_DS1_v2
        admin_username: ansible
        admin_password: "{{ password }}"
        network_interfaces: nic-winweb
        os_type: Windows
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest