---
- hosts: localhost
  connection: local

  tasks:
    - pause:
        prompt: "Enter password"
        echo: no
      when: password is undefined
      register: password_input

    - set_fact:
        password: "{{ password_input.user_input }}"
      when: password is undefined

    - name: 'Linux - Create virtual network'
      azure_rm_virtualnetwork:
        resource_group: ansible
        name: vnet-redis
        address_prefixes: "10.0.0.0/16"

    - name: 'Linux - Add subnet'
      azure_rm_subnet:
        resource_group: ansible
        name: snet-redis
        address_prefix: "10.0.1.0/24"
        virtual_network: vnet-redis

    - name: 'Linux - Create public IP address'
      azure_rm_publicipaddress:
        resource_group: ansible
        allocation_method: Static
        name: pip-redis
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}."

    - name: 'Linux - Create Network Security Group that allows SSH'
      azure_rm_securitygroup:
        resource_group: ansible
        name: nsg-redis
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: 'Linux - Create virtual network interface card'
      azure_rm_networkinterface:
        resource_group: ansible
        name: nic-redis
        virtual_network: vnet-redis
        subnet: snet-redis
        public_ip_name: pip-redis
        security_group: nsg-redis

    - name: 'Linux - Create VM'
      azure_rm_virtualmachine:
        resource_group: ansible
        name: vm-redis
        vm_size: Standard_DS1_v2
        admin_username: ansible
        admin_password: "{{ password }}"
        ssh_password_enabled: true
        network_interfaces: nic-redis
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '8.0'
          version: latest