---
- hosts: all
  gather_facts: false

  # vars_prompt:
  #   - name: password
  #     prompt: "Enter local administrator password"

  vars:
    ansible_user: ubuntu
    #ansible_user: root
    #ansible_password: "{{ password }}"
    #ansible_connection: ssh
    #ansible_password: "P@ssw0rd12344321"
    #become: yes
    ansible_ssh_private_key_file: aws-ansible-key.pem

  tasks:
  - name: run ping
    ping: